//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int AuditLogId { get; set; }
        public Nullable<int> NguoiDungId { get; set; }
        public string HanhDong { get; set; }
        public string DoiTuong { get; set; }
        public string DuLieuTomTat { get; set; }
        public System.DateTime ThoiGianTao { get; set; }
        public string MayTram { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
