//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaLamViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaLamViec()
        {
            this.HoaDonBans = new HashSet<HoaDonBan>();
        }
    
        public int CaLamViecId { get; set; }
        public int NguoiDungId { get; set; }
        public System.DateTime ThoiGianMoCa { get; set; }
        public Nullable<System.DateTime> ThoiGianDongCa { get; set; }
        public string TrangThaiCa { get; set; }
        public string GhiChu { get; set; }
        public decimal TienDauCa { get; set; }
        public Nullable<decimal> TienMatThucDem { get; set; }
        public Nullable<decimal> ChenhLechTienMat { get; set; }
        public string GhiChuDoiSoat { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBan> HoaDonBans { get; set; }
    }
}
