//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHinhHeThong
    {
        public int CauHinhHeThongId { get; set; }
        public string TenQuan { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string FooterHoaDon { get; set; }
        public string LogoPath { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    }
}
