//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDonNhap
    {
        public int ChiTietHoaDonNhapId { get; set; }
        public int HoaDonNhapId { get; set; }
        public int MonId { get; set; }
        public decimal DonGiaNhap { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual HoaDonNhap HoaDonNhap { get; set; }
        public virtual Mon Mon { get; set; }
    }
}
