//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDonBan
    {
        public int ChiTietHoaDonBanId { get; set; }
        public int HoaDonBanId { get; set; }
        public int MonId { get; set; }
        public decimal DonGiaBan { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string KichCo { get; set; }
        public decimal PhuThuKichCo { get; set; }
        public string GhiChuMon { get; set; }
    
        public virtual HoaDonBan HoaDonBan { get; set; }
        public virtual Mon Mon { get; set; }
    }
}
