//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CongThucMon
    {
        public int CongThucMonId { get; set; }
        public int MonId { get; set; }
        public int NguyenLieuId { get; set; }
        public decimal DinhLuong { get; set; }
        public string GhiChu { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Mon Mon { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
