//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonBan()
        {
            this.ChiTietHoaDonBans = new HashSet<ChiTietHoaDonBan>();
            this.LichSuNguyenLieux = new HashSet<LichSuNguyenLieu>();
            this.LichSuTonKhoes = new HashSet<LichSuTonKho>();
        }
    
        public int HoaDonBanId { get; set; }
        public System.DateTime NgayBan { get; set; }
        public decimal TongTien { get; set; }
        public decimal GiamGia { get; set; }
        public Nullable<decimal> ThanhToan { get; set; }
        public int CreatedByUserId { get; set; }
        public string HinhThucThanhToan { get; set; }
        public string TrangThaiThanhToan { get; set; }
        public Nullable<decimal> TienKhachDua { get; set; }
        public Nullable<decimal> TienThoiLai { get; set; }
        public string MaGiaoDich { get; set; }
        public string GhiChuThanhToan { get; set; }
        public string GhiChuHoaDon { get; set; }
        public string LyDoHuy { get; set; }
        public string NguoiHuy { get; set; }
        public Nullable<System.DateTime> NgayHuy { get; set; }
        public Nullable<int> SoThuTuGoiMon { get; set; }
        public Nullable<System.DateTime> NgaySoThuTu { get; set; }
        public string TrangThaiPhaChe { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDauPhaChe { get; set; }
        public Nullable<System.DateTime> ThoiGianHoanThanhPhaChe { get; set; }
        public Nullable<System.DateTime> ThoiGianGiaoKhach { get; set; }
        public string HinhThucPhucVu { get; set; }
        public int DiemSuDung { get; set; }
        public decimal SoTienGiamTuDiem { get; set; }
        public string PaymentProvider { get; set; }
        public string ProviderPaymentId { get; set; }
        public Nullable<long> ProviderOrderCode { get; set; }
        public string QRCodeRaw { get; set; }
        public string CheckoutUrl { get; set; }
        public Nullable<System.DateTime> QRExpiredAt { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentConfirmedAt { get; set; }
        public Nullable<int> BanId { get; set; }
        public Nullable<int> CaLamViecId { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public Nullable<int> KhuyenMaiId { get; set; }
        public decimal SoTienGiam { get; set; }
        public int DiemCong { get; set; }
    
        public virtual Ban Ban { get; set; }
        public virtual CaLamViec CaLamViec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDonBan> ChiTietHoaDonBans { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuNguyenLieu> LichSuNguyenLieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuTonKho> LichSuTonKhoes { get; set; }
    }
}
