//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuNguyenLieu
    {
        public int LichSuNguyenLieuId { get; set; }
        public int NguyenLieuId { get; set; }
        public string LoaiPhatSinh { get; set; }
        public decimal SoLuongThayDoi { get; set; }
        public decimal TonTruoc { get; set; }
        public decimal TonSau { get; set; }
        public Nullable<int> HoaDonBanId { get; set; }
        public Nullable<int> HoaDonNhapId { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public Nullable<int> NguoiDungId { get; set; }
    
        public virtual HoaDonBan HoaDonBan { get; set; }
        public virtual HoaDonNhap HoaDonNhap { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
